---
- name: Include prompts
  import_tasks: prompts.yml

- name: "Upload the SSH key"
  digital_ocean_sshkey:
    oauth_token: "{{ algo_do_token }}"
    name: "{{ SSH_keys.comment }}"
    ssh_pub_key: "{{ lookup('file', '{{ SSH_keys.public }}') }}"
  register: do_ssh_key

- name: "Creating a droplet..."
  digital_ocean_droplet:
    state: present
    name: "{{ algo_server_name }}"
    oauth_token: "{{ algo_do_token }}"
    size: "{{ cloud_providers.digitalocean.size }}"
    region: "{{ algo_do_region }}"
    image: "{{ cloud_providers.digitalocean.image }}"
    wait_timeout: 300
    unique_name: true
    ipv6: true
    ssh_keys: "{{ do_ssh_key.data.ssh_key.id }}"
    tags:
      - Environment:Algo
  register: digital_ocean_droplet

- set_fact:
    cloud_instance_ip: "{{ digital_ocean_droplet.data.ip_address }}"
    ansible_ssh_user: root
