---
- name: Include tasks for Ubuntu
  include_tasks: ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Include tasks for FreeBSD
  include_tasks: freebsd.yml
  when: ansible_distribution == 'FreeBSD'

- name: Include DNS adblocking tasks
  import_tasks: dns_adblocking.yml
  when: algo_dns_adblocking

- block:
  - name: Install dnscrypt-proxy service
    command: "/opt/dnscrypt-proxy/dnscrypt-proxy -service install"
    become: yes
    become_user: root
    changed_when: false

  - name: Start dnscrypt-proxy service
    command: "/opt/dnscrypt-proxy/dnscrypt-proxy -service start"
    become: yes
    become_user: root
    changed_when: false
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- meta: flush_handlers

- name: dnscrypt-proxy enabled and started
  service:
    name: dnscrypt-proxy
    state: started
    enabled: true
