---
- name: Set tor apt
  shell: 
    echo "deb https://deb.torproject.org/torproject.org/ $(lsb_release -cs) main" >> /etc/apt/sources.list.d/tor.list &&
    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 &&
    apt update

- name: Install tor and monit
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - tor
    - tor-geoipdb
    - torsocks
    - deb.torproject.org-keyring
    - monit

- name: disable tor on start
  systemd:
    name: tor
    enabled: no
    masked: no
    state: stopped

- replace:
    path: /etc/monit/monitrc
    regexp: '(\s+)set daemon 120(\s+.*)?$'
    replace: '\1set daemon 60\2'
    backup: yes

- name: update monitrc file messages check
  blockinfile:
    path: /etc/monit/monitrc
    block: |
        check file messages with path /var/log/auth.log
    marker: "# {mark} ANSIBLE MANAGED BLOCK check"

- name: update monitrc with users
  blockinfile:
    path: /etc/monit/monitrc
    block: |
        if match "session opened for user {{ item }}" then exec "/bin/systemctl start tor"
        if match "Disconnected from user {{ item }}" then exec "/bin/systemctl stop tor"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  with_items: "{{ users }}"

- name: restart monit
  systemd:
    name: monit
    enabled: yes
    masked: no
    state: restarted
