---
#- name: install tor project apt signing gpg key
#  apt_key: 
#    state: present
#    data: {{ lookup('file', 'tor-signing-key.pub') }}

- name: Get tor repo key
  shell: |
    curl https://deb.torproject.org/torproject.org/A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89.asc | gpg --import
    gpg --export A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89 | apt-key add -

- apt_repository:
    repo: deb https://deb.torproject.org/torproject.org eoan main
    state: present 
    filename: tor
    update_cache: yes

#- name: Add tor key
#  apt_key:
#    keyserver: keyserver.ubuntu.com
#    id: A3C4F0F979CAA22CDBA8F512EE8CBC9E886DDD89
#    keyring: /etc/apt/trusted.gpg.d/tor.gpg

- name: Install tor and monit
  apt:
    name: ['tor', 'tor-geoipdb', 'torsocks', 'deb.torproject.org-keyring', 'monit']
    state: present

- name: disable tor on start
  systemd:
    name: tor
    enabled: no
    masked: no
    state: stopped

- name: Configure unattended-upgrades
  copy:
    src: 50-tor-unattended-upgrades
    dest: /etc/apt/apt.conf.d/50-tor-unattended-upgrades
    owner: root
    group: root
    mode: 0644

- replace:
    path: /etc/monit/monitrc
    regexp: '(\s+)set daemon 120(\s+.*)?$'
    replace: '\1set daemon 60\2'
    backup: yes

- name: update monitrc file messages check
  blockinfile:
    path: /etc/monit/monitrc
    block: |
        check file messages with path /var/log/auth.log
    marker: "# {mark} ANSIBLE MANAGED BLOCK check"

- name: update monitrc with users
  blockinfile:
    path: /etc/monit/monitrc
    block: |
        if match "session opened for user {{ item }}" then exec "/bin/systemctl start tor"
        if match "Disconnected from user {{ item }}" then exec "/bin/systemctl stop tor"
    marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item }}"
  with_items: "{{ users }}"

- name: restart monit
  systemd:
    name: monit
    enabled: yes
    masked: no
    state: restarted
